-- Aprender com as correções (30/09/2026): o que a IA leu × o que o atendente confirmou ao gerar.
-- leitura_ia: o JSON que a IA devolveu em cada extração (id = o mesmo "leitura" da tabela uso_ia).
-- correcao_ia: uma linha por campo comparado quando um orçamento é gerado a partir de uma leitura
-- (corrigido = o atendente mudou). É daqui que sai o relatório /swagger/qualidade-ia: onde a IA mais erra, por
-- campo, modelo e fornecedor — para ajustar o prompt com base em dado, não em impressão.

CREATE TABLE leitura_ia (
    id        VARCHAR(36) PRIMARY KEY,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL,
    modo      VARCHAR(12) NOT NULL,
    modelo    VARCHAR(60) NOT NULL,
    degrau    INTEGER     NOT NULL,
    arquivos  INTEGER     NOT NULL,
    dados     VARCHAR(20000) NOT NULL
);

CREATE INDEX ix_leitura_ia_criado ON leitura_ia (criado_em);

CREATE TABLE correcao_ia (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criado_em    TIMESTAMP WITH TIME ZONE NOT NULL,
    leitura_id   VARCHAR(36) NOT NULL REFERENCES leitura_ia (id) ON DELETE CASCADE,
    -- o orçamento pode ir para a lixeira e ser apagado de vez: a estatística fica
    orcamento_id BIGINT REFERENCES orcamento (id) ON DELETE SET NULL,
    modelo       VARCHAR(60) NOT NULL,
    campo        VARCHAR(40) NOT NULL,
    -- 0 = campo do cabeçalho; 1..n = linha do orçamento
    item         INTEGER     NOT NULL,
    fornecedor   VARCHAR(120),
    lido         VARCHAR(1000),
    final_       VARCHAR(1000),
    corrigido    BOOLEAN     NOT NULL
);

CREATE INDEX ix_correcao_ia_criado ON correcao_ia (criado_em);
