-- SQL padrão (sem tipos exclusivos do PostgreSQL) para rodar também no H2 dos testes e do perfil local.

CREATE TABLE loja (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero          INTEGER      NOT NULL UNIQUE,
    nome            VARCHAR(120) NOT NULL,
    cnpj            VARCHAR(18)  NOT NULL,
    empresa         VARCHAR(40)  NOT NULL,
    template_codigo VARCHAR(10)  NOT NULL,
    ativa           BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE orcamento (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modo         VARCHAR(10)    NOT NULL,
    loja_id      BIGINT         NOT NULL REFERENCES loja (id),
    titulo       VARCHAR(200)   NOT NULL,
    data_emissao DATE           NOT NULL,
    chamado_num  VARCHAR(100),
    subtotal     NUMERIC(14, 2),
    frete        NUMERIC(14, 2),
    acrescimos   NUMERIC(14, 2),
    total        NUMERIC(14, 2) NOT NULL,
    observacoes  VARCHAR(4000),
    requerente   VARCHAR(120)   NOT NULL,
    gestor       VARCHAR(120)   NOT NULL,
    nome_arquivo VARCHAR(255)   NOT NULL,
    pdf_ref      VARCHAR(500)   NOT NULL,
    criado_por   VARCHAR(120)   NOT NULL,
    criado_em    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX ix_orcamento_criado_em ON orcamento (criado_em DESC);
CREATE INDEX ix_orcamento_chamado ON orcamento (chamado_num);

CREATE TABLE orcamento_item (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orcamento_id   BIGINT         NOT NULL REFERENCES orcamento (id) ON DELETE CASCADE,
    ordem          INTEGER        NOT NULL,
    produto        VARCHAR(200)   NOT NULL,
    descricao      VARCHAR(500),
    quantidade     NUMERIC(12, 3) NOT NULL,
    valor_unitario NUMERIC(14, 2) NOT NULL,
    valor_total    NUMERIC(14, 2) NOT NULL
);
