-- Registro de cada chamada ao Gemini (29/09/2026), para o controle de cota e a tela "Uso da IA" (MANUTENCAO §4).
-- Uma linha por requisição enviada ao Google, com sucesso ou não: é o que conta para o RPM/RPD do plano.
-- "leitura" agrupa as chamadas de uma mesma extração (principal, reserva, degraus, repetições).
-- Guardado por 90 dias (UsoIaService apaga o resto na subida).

CREATE TABLE uso_ia (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    momento           TIMESTAMP WITH TIME ZONE NOT NULL,
    leitura           VARCHAR(36) NOT NULL,
    modelo            VARCHAR(60) NOT NULL,
    degrau            INTEGER     NOT NULL,
    papel             VARCHAR(12) NOT NULL,
    ocorrencia        VARCHAR(20) NOT NULL,
    status_http       INTEGER     NOT NULL,
    tokens_entrada    INTEGER,
    tokens_saida      INTEGER,
    tokens_raciocinio INTEGER,
    estimativa        INTEGER     NOT NULL,
    duracao_ms        BIGINT      NOT NULL,
    modo              VARCHAR(12),
    arquivos          INTEGER     NOT NULL,
    origem            VARCHAR(60)
);

CREATE INDEX ix_uso_ia_momento ON uso_ia (momento DESC);
