-- Fornecedores conhecidos (30/09/2026): quem emitiu cada orçamento, com nome padronizado. A IA lê o nome e o CNPJ
-- como aparecem no documento; o sistema reconhece o fornecedor cadastrado (pelo CNPJ, senão pelo nome ou por um dos
-- "apelidos" — os nomes com que ele já apareceu) e, se não conhece, cadastra ao gerar o orçamento.

CREATE TABLE fornecedor (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(120) NOT NULL,
    cnpj      VARCHAR(18) UNIQUE,
    -- nomes como já apareceram nos documentos, separados por " | " (a IA lê "KABUM COMERCIO ELETRONICO S.A.")
    apelidos  VARCHAR(2000),
    ativo     BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL
);

-- A linha do orçamento aponta para o fornecedor; o texto "fornecedor" (V5) continua com o nome usado no dia.
ALTER TABLE orcamento_item ADD COLUMN fornecedor_id BIGINT REFERENCES fornecedor (id);
ALTER TABLE orcamento_item ALTER COLUMN fornecedor SET DATA TYPE VARCHAR(120);
CREATE INDEX ix_orcamento_item_fornecedor ON orcamento_item (fornecedor_id);

-- O que já existia: as linhas da cotação guardavam a loja (Kabum, Pichau...) como texto. Viram fornecedores.
INSERT INTO fornecedor (nome, criado_em)
SELECT DISTINCT fornecedor, CURRENT_TIMESTAMP FROM orcamento_item WHERE fornecedor IS NOT NULL;

UPDATE orcamento_item SET fornecedor_id = (SELECT f.id FROM fornecedor f WHERE f.nome = orcamento_item.fornecedor)
WHERE fornecedor IS NOT NULL;
